# test_swerve_drive_controller:
#   ros__parameters:
#     update_rate: 10 #Hz

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

#     swerve_drive_controller:
#       type: swerve_drive_controller/SwerveController

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    swerve_drive_controller:
      type: swerve_drive_controller/SwerveController

swerve_drive_controller:
  ros__parameters:

    front_left_wheel_joint: "Leg_front_left_1"
    front_right_wheel_joint: "Leg_front_right_1"
    rear_left_wheel_joint: "Leg_back_left_1"
    rear_right_wheel_joint: "Leg_back_right_1"

    front_left_axle_joint: "Leg_front_left_2"
    front_right_axle_joint: "Leg_front_right_2"
    rear_left_axle_joint: "Leg_back_left_2"
    rear_right_axle_joint: "Leg_back_right_2"

    # center_of_rotation: 0.01 # not used
    wheel_x_offset: 0.5 # Chassis Center to Axle Center
    wheel_y_offset: 0.25227 # Axle Center to Wheel Center
    wheel_radius: 0.085  # Radius of the wheels in meters
    max_steering_angle: 1.57079632679  # Maximum steering angle in radians
    min_steering_angle: -1.57079632679  # Minimum steering angle in radians


    cmd_vel_timeout: 10.0
    use_stamped_vel: false
    odom: odom
    base_footprint: base_footprint
    publishe_rate: 50.0
    enable_odom_tf: true
    open_loop: false

    velocity_threshold: 5.0 # angular velocity of the wheel, in rad/s. 50 is about 4.25 m/s

    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
